# Operaciones con vectores

Antes de pasar directamente a generalizar el método de Newton en varias dimensiones, es necesario aprender algo sobre las operaciones entre vectores. 

En este punto de la carrera, ya deben de saber sumar vectores, multiplicarlos por escalares, hacer productos puntos y productos cruz. ¿Cómo se puede hacer todo eso en Julia? 

Un vector es simplemente un arreglo de números. Ya saben hacer arreglos, así que en realidad ya saben hacer vectores. 

In [1]:
# Ejemplo 1: suma

A = [1;2;3;4]
B = [-3,3.3,1,0.2]

C = A+B
println(C)

[-2.0, 5.3, 4.0, 4.2]


In [2]:
# Ejemplo 2: producto escalar

c = 0.5

D = c*A
println(D)

[0.5, 1.0, 1.5, 2.0]


In [3]:
# Ejemplo 3: producto punto

E = A⋅B
println(E)

7.3999999999999995


Hay además algunas operaciones que quisieramos poderlas aplicar sobre cada uno de los elementos de un vector. Por ejemplo, imaginemos que tenemos el vector $A = [1,1,1,2]$. ¿Cómo interpretarías $A+1$? La respuesta es que no se puede interpretar, porque $1$ es un escalar, mientras que $A$ es un vector. 

Quizá una de las interpretaciones más lógicas sería que se sumara $1$ a todos los elementos de $A$. Para esto usamos un punto antes del operador (o después de la función) para indicar que la operación se lleva acabo sobre todos los elementos de $A$

In [4]:
#Ejemplo 4: Suma un escalar a los elemento de A. 

A = [1;2;3;4]
B = A .+ 1
println(A, B)

#Ejemplo 5: Función seno

C = sin.(A)
println(A, C)

[1, 2, 3, 4][2, 3, 4, 5]
[1, 2, 3, 4][0.841471, 0.909297, 0.14112, -0.756802]


Otra posibilidad es que se quiera crear otro vector el cual difiera sólo en uno de los elementos con respecto a otro vector. Por ejemplo, sumándole un valor c a nuestro elemento i. 

En ese caso esperaríamos que con las operaciones

$B = A$ y 

$B[i] = B[i]+c$ tuviéramos el resultado esperado. Sin embargo Julia no lo hace como esperaríamos por la forma en la que se almacena la información. 

In [5]:
#Ejemplo 6: Suma un escalar a uno elemento de A. Error
A = [1;2;3;4]
B = A
B[2] = B[2]+5
println(A, B)

[1, 7, 3, 4][1, 7, 3, 4]


Cambia tanto el resultado en $A$ como en $B$. Para hacerlo correctamente, lo que uno tiene que hacer es una copia de $A$

In [6]:
#Ejemplo 7: Suma un escalar a uno elemento de A. Correcto
A = [1;2;3;4]
B = copy(A)
B[2] = B[2]+5
println(A, B)

[1, 2, 3, 4][1, 7, 3, 4]


Otra posivilidad es que quieran hacer el producto cruz. Para esto se usa el símbolo de cruz, que se obtiene con \times +tab

In [7]:
#Ejemplo 8: Producto cruz
A = [1;2;3]
B = [2;3;4]
println(A×B)

[-1, 2, -1]


[1] Utiliza tu función para calcular derivadas numéricas para hacer una función que obtenga la derivada parcial de funciones de $\mathbb{R^m} \rightarrow \mathbb{R}$ con respecto a la $i$-esimo variable.

[2] Haz una función que obtenga la derivada del $i$-esimo elemento de una función de $\mathbb{R} \rightarrow \mathbb{R^n}$.

[3] Haz una función que calcule la derivada parcial de la $i$-esima entrada de una funcion de $\mathbb{R^m} \rightarrow \mathbb{R^n}$ con respecto a la $j$-esima variable. 

In [8]:
function der_taylor(f, x, h=0.00001)
    return (f(x + h) - f(x - h)) / (2 * h)
end

der_taylor (generic function with 2 methods)

In [9]:
# [1]
# Necesito saber como es la convención para las funciones de vectores
function i_partial(f, x, i, h=0.00001)
    if i > length(x)
        return error
    end
    x_vector_mas_h = copy(x)*1.
    x_vector_menos_h = copy(x)*1.
    x_vector_mas_h[i] += h
    x_vector_menos_h[i] -= h
    return (f(x_vector_mas_h) - f(x_vector_menos_h)) / (2 * h)
end
    
    

i_partial (generic function with 2 methods)

In [10]:
f(s) = 3s[1]^2 + exp(s[2]*s[1])
x = [2, 1]
i_partial(f, x, 3)

error (generic function with 2 methods)

In [11]:
g(x) = [2x, x^2, 3x]
g

g (generic function with 1 method)

In [12]:
# [2]
function i_derivada(f, x, i, h=0.00001)
    return (f(x + h)[i] - f(x - h)[i]) / (2 * h)
end

i_derivada (generic function with 2 methods)

In [13]:
g(x) = [x^2, 3x]
i_derivada(g, 2, 1)

4.000000000026205

In [14]:
function i_j_partial(f, x, i, j, h=0.00001)
    x_vector_mas_h = copy(x)*1.
    x_vector_menos_h = copy(x)*1.
    x_vector_mas_h[j] = x_vector_mas_h[j] + h
    x_vector_menos_h[j] = x_vector_menos_h[j] - h
    return (f(x_vector_mas_h)[i] - f(x_vector_menos_h)[i]) / (2 * h)
end

    

i_j_partial (generic function with 2 methods)

In [42]:
f(x) = [3x[1]^2, exp(x[1]*x[2])]
x = [2, 2]
i_j_partial(f, x, 1, 1)


12.000000000078613

# Matrices

En Julia también es posible trabajar con matrices de forma muy efectiva. Quizá David los hará re-programar las operaciones con matrices, pero por lo pronto utilizaremos lo que Julia ya tiene pre-instalado. 

El primer paso para trabajar con matrices es saber escribir una: 

In [16]:
# Ejemplo 9: Matrices de 1xn y de nx1

A = [1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

In [17]:
B = [1;2;3;4] 


4-element Array{Int64,1}:
 1
 2
 3
 4

In [18]:
# Ejemplo 10: Matrices de nxm

A = [[1 2];
    [3 4];
    [5 6]]

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [19]:
A = Int64[]
b = [1 2 3]
c = vcat(A, b)

1×3 Array{Int64,2}:
 1  2  3

In [20]:
C = hcat(C, A)
C'

LoadError: ArgumentError: number of rows of each array must match (got (4, 0))

El siguiente paso es poder hacer operaciones. Las sumas, y productos escalares, se hacen tal cual como con los vectores: 

In [21]:
# Ejemplo 11: suma y producto escalar
A = [[1 2];
    [3 4];
    [5 6]]
B = [[.1 .2];
    [.3 .4];
    [.5 .6]]
A+B

3×2 Array{Float64,2}:
 1.1  2.2
 3.3  4.4
 5.5  6.6

In [22]:
3*B

3×2 Array{Float64,2}:
 0.3  0.6
 0.9  1.2
 1.5  1.8

El siguiente paso es sacar la transpuesta:

In [23]:
#Ejemplo 12: transpuesta

A = [[1 2];
    [3 4];
    [5 6]]
transpose(A)

2×3 Array{Int64,2}:
 1  3  5
 2  4  6

Ahora ya podemos hacer productos matriciales!!!

In [55]:
# Ejemplo 13: producto matricial
A = [[1 2];
    [3 4];
    [5 6]]
B = transpose(A)*2.3
A

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [25]:
B*A

2×2 Array{Float64,2}:
  80.5  101.2
 101.2  128.8

Por último, algo en extremo útil (para resolver sistemas de ecuaciones, por ejemplo) es obtener la inversa de una matriz. Hay métodos más eficientes para resolver sistemas de matrices, que seguramente verán con David, pero por ahora bastará con obtener la inversa. 

In [26]:
#Ejemplo 14: Inversa de una matriz

A = [[1.2 2.5 3];
    [3 4 5.3];
    [5 6.8 7]]
B = A^-1

A*B

3×3 Array{Float64,2}:
  1.0          8.88178e-16   0.0        
 -3.88578e-16  1.0          -8.88178e-16
 -7.77156e-16  8.88178e-16   1.0        

[4] Resuelve numpericamente el siguiente sistema de ecuaciones: 

$$ 2x_1 + 2.5x_2 -4x_3 +5.33x_4 = 3\\
 3x_1 + 1.5x_2 -2x_3 -1.2x_4 = 1\\
 x_1 - 6x_2 +3x_3 -3.x_4 = 22\\
 12x_1 - 2.5x_2 +x_3 +8.1x_4 = 0$$

[5] Usando la función calculada en [3] haz otra función que calcule la matriz Jacobiana de una función vectorial  de $\mathbb{R^m} \rightarrow \mathbb{R^n}$

[6] Usa lo del ejercicio [17] de la primera parte de la tarea 3 para hacer una función que calcule las raices de funciones vectoriales. 

*** Nota: NO OLVIDES GUARDAR TODAS LAS FUNCIONES IMPORTANTES QUE HAYAS PROGRAMADO EN ESTA TAREA EN TU ARCHIVO "herramientas.jl" ***

In [27]:
# [4]
A = [
    [2 2.5 -4 4.33];
    [3 1.5 -2 -1.2];
    [1 -6 3 -3];
    [12 -2.5 1 8.1]
]
b = [3; 1; 22; 0]
x_sol = A^-1 * b

4-element Array{Float64,1}:
 -0.444901
 -6.18294 
 -5.45944 
 -0.575197

In [28]:
# [5]
function matriz_jacobiana(f, x)
    jacob = Float64[]
    for i = 1:length(x)
        fila = Float64[]
        for j = 1:length(f(x))
            push!(fila, i_j_partial(f, x, i, j))
        end
        if i == 1
            jacob = vcat(jacob, fila)
        else
            jacob = hcat(jacob, fila)
        end
    end
    return transpose(jacob)
end

matriz_jacobiana (generic function with 1 method)

In [74]:
function newton_multivariable(f, x0, ϵ=0.001)
    x = copy(x0)
    x1 = copy(x0)
    n = 0
    δ = 1
    while δ >= ϵ
        n += 1
        x1 = x - ((matriz_jacobiana(f, x)^(-1)) * f(x))
        δ = norm(x1 - x)
        x = x1
        println(n)
        if n > 10000
            return x1
        end
    end
    return x1
end

newton_multivariable (generic function with 2 methods)

In [77]:
norm([1,2,3] - [1,1,5])

2.23606797749979

In [101]:
function newton_multi(f, x0, ϵ=1e-5)
    x = copy(x0) * 1.
    x1 = copy(x) * 1.
    n = 0
    δ = 1
    while δ >= ϵ
        n += 1
        x1 = x - ((matriz_jacobiana(f, x))^(-1) * f(x))
        δ = norm(x1 - x)
        x = x1
        if n > 10000
            return x
        end
    end
    return x
end

newton_multi (generic function with 2 methods)

[7] Resuelve el siguiente sistema de ecuaciones numéricamente y comprueba el resultado (evalua los valores de las $x_i$ en las ecuaciones): 

$$ exp(x_1) + cos(x_2) -4x_3^4 +5.33x_4^2 = 3$$
$$ 3x_1^4 + 1.5x_2^{-1} -2x_3^3 -1.2x_4^3 = 1$$
$$ sin(x_1) - 6x_2 +x_3 -3.2x_4^2 = 22$$
$$ 12x_1^{-1} - 2.5x_2 +x_3^2 +8.1x_4^3 = 0$$

In [103]:
s(x) = [exp(x[1]) + cos(x[2]) - 4(x[3]^4) + 5.33(x[4]^2) - 3, 3(x[1]^4) + (1/(1.5x[2])) - 2(x[3]^3) - 1.2(x[4]^3) - 1,
        sin(x[1]) - 6x[2] + x[3] - 3.2(x[4]^2) - 22, 1/(12x[1]) - 2.5x[2] + (x[3]^2) + 8.1(x[4]^3)]

x = [1., 1., 2., 3.]
#matriz_jacobiana(s, x)^(-1)

newton_multi(s, x)


4-element Array{Float64,1}:
 -0.821455
 -4.30278 
  0.988974
 -1.12826 

In [36]:
# Prueba del funcionamiento de la funcion jacobiana
f(x) = [x[1]^2, x[1]^2*x[2]]
x = [2., 3.]
matriz_jacobiana(f, x)

2×2 Array{Float64,2}:
  4.0  0.0
 12.0  4.0

Parece que la función que calcula la matriz jacobiana está bien, ¿Cuál podría ser el error?

In [89]:
# Otra prueba de la función del jacobiano
f(x) = [2x[1]x[2], (x[1]^2)*(x[2]^2)*(x[3]), 3(x[1])*(x[2]^2)*(x[3]^3)]
x = [2., 3., 4.]
matriz_jacobiana(f, x)

3×3 Array{Float64,2}:
    6.0     4.0     0.0
  144.0    96.0    36.0
 1728.0  2304.0  2592.0

In [44]:
f(x) = [2x[1]x[2], (x[1]^2)*(x[2]^2)*(x[3]), 3x[1]x[2]^2x[3]^3]
x = [1., 1., 1.]
i_j_partial(f, x, 2, 2)

2.000000000002

In [62]:
s(x) = [exp(x[1]) + cos(x[2]) - 4(x[3]^4) + 5.33(x[4]^2) - 3, 3(x[1]^4) + 1.5(x[2]^(-1)) - 2(x[3]^3) - 1.2(x[4]^3) - 1,
        sin(x[1]) - 6x[2] + x[3] - 3.2(x[4]^2) - 22, 12(x[1]^(-1)) - 2.5x[2] + (x[3]^2) + 8.1(x[4]^3)]
x = [1., 1., 1., 1.]

A = matriz_jacobiana(s, x)


4×4 Array{Float64,2}:
   2.71828   -0.841471  -16.0  10.66
  12.0       -1.5        -6.0  -3.6 
   0.540302  -6.0         1.0  -6.4 
 -12.0       -2.5         2.0  24.3 

In [60]:
s(x)

4-element Array{Float64,1}:
   1.58858
   0.3    
 -29.3585 
  18.6    

In [64]:
A*s(x)

4-element Array{Float64,1}:
  672.078
  127.804
 -149.34 
  373.45 

In [92]:
zeros(x)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0